export const TYPES = {
    FETCH_DATA: "FETCH_DATA",
    TOGGLE_CART: "TOGGLE_CART",
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_GOODS_COUNT: "UPDATE_GOODS_COUNT",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    SET_LOCAL_CART: "SET_LOCAL_CART",
};
